auto-commit-message: "#{git-auto}"
watch:

  - files: ./*.cr
    run: "crystal build #{file}"
    git: none

  - files: ./src/**/*.cr
    run: "shards build"
    git: add

  - files: ./spec/**/*.cr
    run: "echo \"#{file} is changed\""
    git: add

  - files: ./shard.yml
    run: "shards update"
    git: add

  - files: ./*.py
    run: "echo \"#{file} is changed\""
    git: none
