# name of the file in any project
target: .warden.yml

max-substitution-layer: 30

# delay in ms between two check ( min = 250ms )
delay:   1000
# delay be
timeout: 2000

# pre implemented commands
#    #{file}     -> current file (path + base + ext )
#    #{basename} -> name of the file without extension (e.g. "./src/warden.cr" -> "warden")
#    #{extname}  -> pextension (e.g. "main.cr" -> "cr" ) 
#    #{path}     -> path of the current file (e.g. "./src/warden.cr" -> "./src/")
#    #{pwd}      -> absolute path of the current directory.
#    #{cwd}      -> idem. More natural for C/C++/python users
#    #{dirname}  -> name of the current direcory
#
#  - files   -> glob for file analysis
#    run     -> command to run for the files
#    git     -> command git to run (none|add|commit|push|pull)
#    timeout -> custom timeout

precommand:
  # README.md
  - files: ./README.md
    git: add
  # changelog.md
  - files: ./changelog.md
    git: add
  # CHANGELOG
  - files: ./CHANGELOG.md
    git: add

  # LICENCE
  - files: ./LICENCE
    git: add
  
  # travis file
  - files: ./.travis.yml
    git: add

  # crystal - sources
  - files: ./src/**/*.cr
    run: shards build
    git: add
    timeout: 10000
  # crystal spec
  - files: ./spec/**/*.cr
    git: add

  # some crystal files
  - files: ./*.cr
    run: "crystal run \"#{file}\""
  # shards
  - files: ./shard.yml
    run: shards update
    git: add
    timeout: 10000


  # C sources (basic)
  - files: ./src/*.c
    run: "gcc -c \"#{file}\" -o \"#{basename}.o\" -O3 -Wall -Wextra"
    git: add
  - files: ./src/*.h
    run: "gcc -c \"#{path}#{basename}.c\" -o \"#{basename}.o\" -O3 -Wall -Wextra"
    git: add
  - files: ./src/main.c
    run: make -j
    git: commit

  # python
  - files: ./**/*.py
    git: add
  
  # java
  - files: ./**/*.java
    run: "javac \"#{file}\""
    git: add

  # shell / bash
  - files: ./**/*.sh
